### ISSUE TITLE
iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by aelaa** [tungkradle/aseprite-than#2]
libpng crashing app with segfault with this error. I think your png files is not so clean.

**Comment by lettdev** [comment]
Thanks for feedback, fixed it! Please let me know if you still have the problem

**Comment by aelaa** [comment]
No warning now, but still have fault :(
Here is debug info, maybe helps you.
```
Thread 1 "aseprite" received signal SIGSEGV, Segmentation fault.
ui::Widget::textHeight (this=this@entry=0xf77f80) at ../src/ui/widget.cpp:762
762       return font()->height();
```
Other themes is working good (https://github.com/michidk/Aseprite-DarkFlat-Theme for example)

**Comment by lettdev** [comment]
I see. May I ask what version of Aseprite are you using? Current version of this theme only supports Aseprite v1.2 beta 8 or later, and it seems like you are using an older version of aseprite because DarkFlat theme works fine with you. 

In this case I suggest you download and use [than v1.1.1](https://github.com/tungkradle/aseprite-than/releases/tag/v1.1.1b)

**Comment by aelaa** [comment]
@tungkradle I built it manually from Aseprite master branch just before installing your theme. It shows version 1.2-dev now

**Comment by lettdev** [comment]
That sounds really strange because I tested it a lot with beta8 and b9 build and pretty sure there was no problem except the libpng warning (and it has nothing to do with the segmentation fault). 
Beside, DarkFlat theme should not have worked with the new theme system (it will cause segmentation fault with b8 and b9), so if it works with your current Aseprite then you may be running an older version. 
Keep in mind that _only beta 8 or later_ has the new theme system, so even _1.2-dev beta 7_ build won't work. What OS are you using? Can you rebuild aseprite and test it again?
